title:               15th Shaban Celebration
url:                 https://erssec.github.io/
baseurl:             "/celeste"

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Cheshmberah
  url:               15th-shaban.org
  email:             n/a

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist